spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tera
    username: user
    password: password # username, password 암호화 필요

  jpa:
    hibernate:
      ddl-auto: create #실제론 사용 X
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
